### PR TITLE
manually loaded audio to fix forwarding issue

### LINKED ISSUE #17: audio playback bar audio gets stuck
Assuming the audio is shorter than 15 seconds:
1. If audio is fast-forwarded while playing then audio gets stuck and only fixes after refresh
2. When paused, if the audio is rewinded and then fast-forwarded, the audio also gets stuck and the page needs to be refreshed.
3. If the page is refreshed on a slide with audio, the audio play button will display the 'play' version but the audio will not play because the user has not interacted with the page yet.

### PR DESCRIPTION
**Pull request by kimmy190**
* fixed the audio bug #17 by loading the audio when its not ready to be played yet

### CODE REVIEW

File: v2/audio.js [hunk 1]
```diff
@@ -19,9 +19,24 @@
             // Play button click event
             this.playBtn.addEventListener('click', () => {
                 if (this.audio.paused) {
-                    this.audio.play();
+                    // make sure the audio is ready to be played 
+                    console.log(this.audio.readyState);
+                    if (this.audio.readyState < 3) {
+                        // forces reloading the buffer when audio is
```
Comment (daexs) [inline v2/audio.js]: I am a little confused what's happening here, maybe we could add a comment to clarify a bit more.

**Review by daexs — CHANGES_REQUESTED** [review]
Everything looks good to me! One comment can be modified to make the code clearer.

**Review by daexs — APPROVED** [review]
looks good!
